import Bed from './bed.jpg';
import Exercise from './exercise.jpg';
import man from './man.jpg';
import tennis from './tennis.jpg';
import ToLink from './toOpenKakao.png';
import Logo from './logo.png';

export const training_column_db = [
  {
    id: 18,
    category: 'training',
    title: '필라테스로 바디프로필 찍기',
    img: Exercise,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-11',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
    type: 'html',
    description: 'html이었다잇',
  },
  {
    id: 17,
    category: 'training',
    title: '휴식의 중요성',
    img: Bed,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-09',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
    type: 'card-news',
    cardNews: [Bed, Exercise, man, tennis],
    description: '사진들을 보고 공부하세요',
  },
  {
    id: 16,
    category: 'training',
    title: '효율적인 다이어트 방법',
    img: man,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-08',

    type: 'video',
    video: [
      'https://www.youtube.com/watch?v=tYHgOCT68VE',
      'https://www.youtube.com/watch?v=tIdtmy3gXkU',
    ],
    description: '위의 영상들을 보고 느낀점이 있으셨나요? ^^',
  },
  {
    id: 15,
    category: 'training',
    title: '침대',
    img: tennis,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-05',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
    type: 'html',
  },
  {
    id: 14,
    category: 'training',
    title: '일하고싶다',
    img: Bed,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-03',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
    type: 'html',
  },
  {
    id: 13,
    category: 'training',
    title: '바디칼럼',
    img: man,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-01',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
    type: 'card-news',
  },
];

export const nutrition_column_db = [
  {
    id: 12,
    category: 'nutrition',
    title: '영양학 8',
    img: man,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-11',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
    type: 'html',
  },
  {
    id: 11,
    category: 'nutrition',
    title: '맛있는거 먹기',
    img: Bed,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-09',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
    type: 'card-news',
  },
  {
    id: 10,
    category: 'nutrition',
    title: '효율적인 식단 방법',
    img: man,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-08',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
    type: 'video',
  },
  {
    id: 9,
    category: 'nutrition',
    title: '영양',
    img: tennis,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-05',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
    type: 'html',
  },
  {
    id: 8,
    category: 'nutrition',
    title: '밥 먹자',
    img: Bed,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-03',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
    type: 'card-news',
  },
  {
    id: 7,
    category: 'nutrition',
    title: '바디칼럼',
    img: tennis,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-01',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
    type: 'video',
  },
  {
    id: 6,
    category: 'nutrition',
    title: '영양칼럽',
    img: tennis,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-01',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
    type: 'card-news',
  },
  {
    id: 5,
    category: 'nutrition',
    title: '호잇',
    img: Exercise,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-01',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
    type: 'html',
  },
];

export const photo_column_db = [
  {
    id: 4,
    category: 'photo',
    title: '촬영팁',
    img: tennis,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-03',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
    type: 'card-news',
  },
  {
    id: 3,
    category: 'photo',
    title: '촬영 시 뭐할까',
    img: Exercise,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-01',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
    type: 'card-news',
  },
  {
    id: 2,
    category: 'photo',
    title: '정상수의 웹캠 팁',
    img: Bed,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-01',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
    type: 'html',
  },
  {
    id: 1,
    category: 'photo',
    title: '남자다',
    img: man,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-01',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
    type: 'card-news',
  },
];
