import Bed from './bed.jpg';
import Exercise from './exercise.jpg';
import Posing from './기본 포징.png';
import man from './man.jpg';
import tennis from './tennis.jpg';
import ToLink from './toOpenKakao.png';
import Logo from './logo.png';
import Wedidit from './wedidit.png';
import ToStudio from './toStudio.png';
import Wedidit1 from './wedidit1.png';
export const training_column_db = [
  {
    id: 18,
    category: 'photo',
    title: '포징의 기본기, 스탠다드한 포징',
    img: Wedidit1,
    logo: Wedidit,
    writer: '위디딧',
    updateDate: '2021-10-11',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToStudio,
  },
  {
    id: 17,
    category: 'photo',
    title: '포징의 기본기, 스탠다드한 포징',
    img: Posing,
    logo: Wedidit,
    writer: '위디딧',
    updateDate: '2021-10-09',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToStudio,
  },
  {
    id: 16,
    category: 'training',
    title: '효율적인 다이어트 방법',
    img: man,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-08',

    video: [
      'https://www.youtube.com/watch?v=tYHgOCT68VE',
      'https://www.youtube.com/watch?v=tIdtmy3gXkU',
    ],
  },
  {
    id: 15,
    category: 'training',
    title: '침대',
    img: tennis,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-05',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
    type: 'html',
  },
  {
    id: 14,
    category: 'training',
    title: '일하고싶다',
    img: Bed,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-03',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
  },
  {
    id: 13,
    category: 'training',
    title: '바디칼럼',
    img: man,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-01',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
  },
];

export const nutrition_column_db = [
  {
    id: 12,
    category: 'nutrition',
    title: '영양학 8',
    img: man,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-11',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
  },
  {
    id: 11,
    category: 'nutrition',
    title: '맛있는거 먹기',
    img: Bed,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-09',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
  },
  {
    id: 10,
    category: 'nutrition',
    title: '효율적인 식단 방법',
    img: man,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-08',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
  },
  {
    id: 9,
    category: 'nutrition',
    title: '영양',
    img: tennis,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-05',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
  },
  {
    id: 8,
    category: 'nutrition',
    title: '밥 먹자',
    img: Bed,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-03',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
  },
  {
    id: 7,
    category: 'nutrition',
    title: '바디칼럼',
    img: tennis,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-01',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
  },
  {
    id: 6,
    category: 'nutrition',
    title: '영양칼럽',
    img: tennis,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-01',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
  },
  {
    id: 5,
    category: 'nutrition',
    title: '호잇',
    img: Exercise,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-01',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
  },
];

export const photo_column_db = [
  {
    id: 4,
    category: 'photo',
    title: '촬영팁',
    img: tennis,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-03',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
  },
  {
    id: 3,
    category: 'photo',
    title: '촬영 시 뭐할까',
    img: Exercise,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-01',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
  },
  {
    id: 2,
    category: 'photo',
    title: '정상수의 웹캠 팁',
    img: Bed,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-01',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
  },
  {
    id: 1,
    category: 'photo',
    title: '남자다',
    img: man,
    logo: Logo,
    writer: '바디포즈',
    updateDate: '2021-10-01',
    toLink: 'https://bodypose.co.kr',
    toLinkImg: ToLink,
  },
];
