export const ARTICLE_CATEGORY_NOT_FOUND = 'ARTICLE_CATEGORY_NOT_FOUND';
export const EDITOR_NOT_FOUND = 'EDITOR_NOT_FOUND';
export const NO_ARTICLE_CATEGORIES = 'NO_ARTICLE_CATEGORIES';
export const ARTICLE_NOT_FOUND = 'ARTICLE_NOT_FOUND';
